#========================================================#
#        _____          _       _    _                   #
#       |  __ \        | |     | |  | |                  #
#       | |__) |___  __| | __ _| | _| |_ ___  _ __       #
#       |  _  // _ \/ _` |/ _` | |/ / __/ _ \| '__|      #
#       | | \ \  __/ (_| | (_| |   <| || (_) | |         #
#       |_|  \_\___|\__,_|\__,_|_|\_\\__\___/|_|         #
#                                                        #
#========================================================#

schematics:

    # Should schematics that are saved be put in
    # a folder named after the player's uuid
    # in the Redaktor folder?
    uuid-folder: true