#===================================================#
#     _____          _       _    _                 #
#    |  __ \        | |     | |  | |                #
#    | |__) |___  __| | __ _| | _| |_ ___  _ __     #
#    |  _  // _ \/ _` |/ _` | |/ / __/ _ \| '__|    #
#    | | \ \  __/ (_| | (_| |   <| || (_) | |       #
#    |_|  \_\___|\__,_|\__,_|_|\_\\__\___/|_|       #
#                                                   #
#===================================================#

# Select which language you want
# Default languages: en (english), ne (dutch)
# You can also add languages yourself.
language: en

# Change count
# Here you can change how many blocks per 1/20th of a second can be changed.
# Default: 2000.
change: 2000